backend:
  name: git-gateway
  


collections:
  - name: "posts"
    label: "Notes"
    folder: "posts"
    create: true
    slug: "{{ slug }}"
    fields:
      - {
        label: "Title", 
        name: "title", 
        widget: "string"
      }


media_folder: "./site/images"